#!/bin/bash -l
# SLURM resource specifications
#SBATCH --job-name=n500 # shows up in the output of ‘squeue’
#SBATCH --time=6:00:00       # specify the requested wall-time
#SBATCH --partition=astro2_short # specify the partition to run on
#SBATCH --nodes=1              # number of nodes allocated for this job
#SBATCH --ntasks-per-node=1    # number of MPI ranks per node
#SBATCH --cpus-per-task=4      # number of OpenMP threads per MPI rank
#SBATCH --mail-type=ALL
#SBATCH --array=0-0
echo "now processing task id:: " ${SLURM_ARRAY_TASK_ID}

#all times in terms of orbits

#is the run continuing? 0 - no, 1- yes
cont=1

#initial time of the run
tinit=2.0

#previous output time
tprevious=1.0

#end time of run
tend=3.0
#dust composition
#composition='OlSL'
#composition='OlSC'
#composition='MgFeSiO4'
composition='Mg08Fe12SiO4'
#composition='Mg2SiO4'
#composition='Mg095Fe005SiO3'
#directory='Mg095Fe005SiO3/distributions/'
#directory='Olivine_SL/distributions/'
#directory='Mg08Fe12SiO4/jun23/KIC1255b/tauc/'
directory='Mg08Fe12SiO4/jun23/KIC1255b/tauc/n500/'
#directory='Olivine_SC/distributions/'
#directory='MgFeSiO4/distributions/'
#directory='Mg08Fe12SiO4/K222b/'
#directory='Mg2SiO4/jan23/'
#directory='Olivine_SL/K222b/'
#planet - options are KIC1255b or K222b
#planet='K222b'
planet='KIC1255b'

#orbit directory name, previous orbit directory name
orbit='2nd_orb'
p_orbit='1st_orb'

#particle size distribution
s_dist=0   #1 for yes, 0 for no
dist_type=0  #0 for normal dist, 1 for log-normal dist, 2 for power law
mu=-1.25   #for power law, mu is n
sigma=0.61  #standard deviation !!! ^^^^
mdot=2.0
gm=1
# outdir=/lustre/astro/bmce/Dusty_Tails/simulations/${directory}/mu${mu}_sigma${sigma}_log${lognormal} #only for size distributions

# #create directory if it does not exist
# if [ ! -d ${outdir} ]
# then
# mkdir ${outdir}
# fi

#NOTE!! MDOT AND OUTFLOW GEOMETRY DEFINED IN INPUT/INPUT_GRID_SHORT.CSV
#WHEN NOT RUNNING A GRID OF MODELS
#size,mdot,geom
#grid of models in paper used was INPUT/INPUT_GRID.CSV


# define and create a unique scratch directory
SCRATCH_DIRECTORY=/lustre/astro/bmce/Dusty_Tails/scratch/${SLURM_JOBID}
mkdir -p ${SCRATCH_DIRECTORY}
cd ${SCRATCH_DIRECTORY}
echo ${SCRATCH_DIRECTORY}
echo ${SLURM_SUBMIT_DIR}

#writting input file 2
cat << EOF > run.in
${SLURM_ARRAY_TASK_ID}
${cont}
${tinit}
${tend}
${composition}
${s_dist}
${dist_type}
${mu}
${sigma}
${mdot}
${gm}
EOF

cp -r ${SLURM_SUBMIT_DIR}/executables ./
cp ${SLURM_SUBMIT_DIR}/src/*.o ./
cp ${SLURM_SUBMIT_DIR}/input/* ./
cp -r ${SLURM_SUBMIT_DIR}/opacs_jankovic/ ./

cp distributions.in distributions.in
cp n_pow_dist3.dat n_pow_dist.dat

if [ $s_dist == 0 ]
then
cp ${SLURM_SUBMIT_DIR}/input/input_grid_short2.csv ./input_grid.csv
elif [ $s_dist == 1 ]
then
cp ${SLURM_SUBMIT_DIR}/input/input_grid_short2.csv ./input_grid.csv
#cp ${SLURM_SUBMIT_DIR}/input/input_grid_short2.csv ./input_grid.csv
fi

mkdir data
python3 input.py > python.out
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

#input with planet, star and optical depth grid info
#cp ./dusty_tails_${planet}_tauc.in dusty_tails.in
#cp ./dusty_tails_${planet}_n100.in dusty_tails.in
cp ./dusty_tails_${planet}_n500.in dusty_tails.in
input_file='input.txt'
n=1
while read line; do
# reading each line
if [ $n == 1 ]
then
s_0=$line
echo $s_0
fi
if [ $n == 2 ]
then
mdot=$line
echo $mdot
fi
if [ $n == 3 ]
then
geom=$line
echo $geom
fi
if [ $n == 9 ]
then
mu=$line
echo $mu
fi
if [ $n == 10 ]
then
sigma=$line
echo $sigma
fi
n=$((n+1))
done < $input_file

if [ $geom == 0 ]
then
geom_s='day'
elif [ $geom == 1 ]
then
geom_s='sph'
fi
echo $geom_s


outdir=/lustre/astro/bmce/Dusty_Tails/simulations/${directory}/n${mu}_powdist_dist3_tauc_n100_1.0e-9/
mkdir -p ${outdir}

if [ $cont == 1 ]
then

if [ $s_dist == 1 ]
then
input_dir=${outdir}/mdot${mdot}_${geom_s}_t${tprevious}
elif [ $s_dist == 0 ]
then
input_dir=/lustre/astro/bmce/Dusty_Tails/simulations/${directory}/${p_orbit}/s${s_0}_mdot${mdot}_${geom_s}_t${tprevious}
fi

echo ${input_dir}
cp ${input_dir}/output_final_struct.bin input.bin
fi

if [ $s_dist == 0 ]
then
mkdir -p /lustre/astro/bmce/Dusty_Tails/simulations/${directory}/${orbit}
id_dir=/lustre/astro/bmce/Dusty_Tails/simulations/${directory}/${orbit}/s${s_0}_mdot${mdot}_${geom_s}_t${tinit}
elif [ $s_dist == 1 ]
then
id_dir=${outdir}/mdot${mdot}_${geom_s}_t${tinit}
fi

echo ${id_dir}
mkdir -p ${id_dir}

time ./executables/dusty_tails.exe > run.out

mv ./data/output.bin        ${id_dir}/output_struct.bin
mv ./data/output_final.bin  ${id_dir}/output_final_struct.bin
mv ./data/light_curve.bin   ${id_dir}/light_curve.bin
mv ./data/tau_data.bin      ${id_dir}/tau_data.bin
# mv gmon.out                 ${id_dir}/gmon.out
mv run.in                   ${id_dir}/run.in
mv run.out                  ${id_dir}/runlog.out

cd ${SLURM_SUBMIT_DIR}
cp slurm-${SLURM_JOBID}_0.out ${id_dir}
#rm -rf slurm-${SLURM_JOBID}_0.out
rm -rf ${SCRATCH_DIRECTORY}
exit 0