#!/bin/csh
#makeinput
#/dev/shm/uffegj

#KOPIER MARCS TIL $TMPDIR
# cp ..... $TMPDIR/
# cd $TMPDIR
# ...koer marcs...
# mv mxmodel.dat $CWD/...
# cd $CWD
# rm -rf $TMPDIR 
#
#

setenv CWD `pwd`
setenv TMPDIR `mktemp -p /dev/shm/ -u`
mkdir $TMPDIR
cp -r ./* $TMPDIR/.
cd $TMPDIR 

#***************************

./executables/dusty_tails.exe

mv ./data/output_struct.bin  $CWD/simulations/K222b_03micro_1mdot_day_05orb_tc.bin
mv ./data/output_final.bin  $CWD/simulations/K222b_03micro_1mdot_day_05orb_tc_final.bin

rm -rf $TMPDIR
